//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltaMedica
    {
        public int idAlta { get; set; }
        public Nullable<int> idIngreso { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idHabitacion { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Ingresos Ingresos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
