//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingresos()
        {
            this.AltaMedica = new HashSet<AltaMedica>();
        }
    
        public int idIngreso { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<int> idHabitacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AltaMedica> AltaMedica { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
